const seedCars = [
  { id: 'velvet', name: 'VELVET // RS', driver: '@ravenbuilds', game: 'cpm', votes: 0 },
  { id: 'sundown', name: 'SUNDOWN 86', driver: '@milesahead', game: 'demo', votes: 0 },
  { id: 'mono', name: 'MONOCHROME', driver: '@lowkey.luis', game: 'cpm', votes: 0 },
  { id: 'apex', name: 'APEX // 07', driver: '@kaito.cpm', game: 'demo', votes: 0 },
  { id: 'nightshift', name: 'NIGHTSHIFT', driver: '@sienna.drives', game: 'cpm', votes: 0 },
  { id: 'orbit', name: 'ORBIT GT', driver: '@orbitals', game: 'demo', votes: 0 },
];
function readStorage(key, fallback) { try { const value = JSON.parse(localStorage.getItem(key) || 'null'); return value === null ? fallback : value; } catch (error) { return fallback; } }
function cleanCar(car) { return { id: String(car?.id || `car-${Date.now()}`), name: String(car?.name || 'UNTITLED BUILD').slice(0, 40), driver: String(car?.driver || '@unknown').slice(0, 28), game: car?.game === 'demo' ? 'demo' : 'cpm', votes: Number.isFinite(Number(car?.votes)) && Number(car.votes) >= 0 ? Math.floor(Number(car.votes)) : 0, comments: Array.isArray(car?.comments) ? car.comments.filter((comment) => comment && typeof comment.text === 'string').slice(-20).map((comment) => ({ text: comment.text.slice(0, 20), author: String(comment.author || '@driver').slice(0, 28) })) : [] }; }
let cars = (Array.isArray(readStorage('garageCars', null)) ? readStorage('garageCars', []) : seedCars).map(cleanCar);
let voted = Array.isArray(readStorage('garageVotes', [])) ? readStorage('garageVotes', []).filter((id) => typeof id === 'string') : [];
let accounts = Array.isArray(readStorage('garageAccounts', [])) ? readStorage('garageAccounts', []).filter((account) => account && typeof account.parkingId === 'string') : [];
let currentAccount = readStorage('garageSession', null);
currentAccount = currentAccount && typeof currentAccount.parkingId === 'string' ? { parkingId: currentAccount.parkingId.slice(0, 24).toUpperCase() } : null;
let authMode = 'login';
let activeFilter = 'all';
const $ = (selector) => document.querySelector(selector);
const toast = (message) => { const el = $('#toast'); el.textContent = message; el.classList.add('show'); setTimeout(() => el.classList.remove('show'), 2600); };
const validParkingId = (value) => /^[A-Z0-9-]{6,24}$/i.test(value.trim());
const assistantMessages = $('#assistant-messages');
const escapeHtml = (value) => value.replace(/[&<>"']/g, (character) => ({ '&': '&amp;', '<': '&lt;', '>': '&gt;', '"': '&quot;', "'": '&#039;' }[character]));
function addAssistantMessage(text, type = 'assistant', source = '') { const message = document.createElement('div'); message.className = `assistant-message ${type}`; message.innerHTML = `<p>${escapeHtml(text)}</p>${source ? `<small>Source: ${escapeHtml(source)}</small>` : ''}`; assistantMessages.appendChild(message); assistantMessages.scrollTop = assistantMessages.scrollHeight; }
function localAssistantAnswer(query) { const normalized = query.toLowerCase(); if (normalized.includes('vote') || normalized.includes('voting')) return 'Log in with your Car Parking ID, then select one build and press its heart button. Each account can vote for a build once per week.'; if (normalized.includes('submit') || normalized.includes('enter') || normalized.includes('build')) return 'Use the submission section to choose CPM or CPM Demo and name your build. A verified Car Parking ID is required before the entry can go live.'; if (normalized.includes('login') || normalized.includes('sign up') || normalized.includes('account')) return 'Use Log in in the top bar. New players can choose Sign up and create a local demo account with their Car Parking ID.'; if (normalized.includes('garage weekly') || normalized.includes('this website')) return 'Garage Weekly is a weekly community showcase where CPM players submit builds, vote, and compete for the cover.'; return ''; }
async function answerAssistant(query) { const localAnswer = localAssistantAnswer(query); if (localAnswer) { addAssistantMessage(localAnswer); return; } const loading = document.createElement('div'); loading.className = 'assistant-message assistant is-loading'; loading.innerHTML = '<p>Checking public sources...</p>'; assistantMessages.appendChild(loading); assistantMessages.scrollTop = assistantMessages.scrollHeight; try { const response = await fetch(`https://en.wikipedia.org/w/api.php?action=query&list=search&srsearch=${encodeURIComponent(query)}&srlimit=1&format=json&origin=*`); if (!response.ok) throw new Error('Lookup failed'); const result = await response.json(); const match = result.query?.search?.[0]; if (!match) throw new Error('No result'); const summaryResponse = await fetch(`https://en.wikipedia.org/api/rest_v1/page/summary/${encodeURIComponent(match.title.replaceAll(' ', '_'))}`); if (!summaryResponse.ok) throw new Error('Summary unavailable'); const summary = await summaryResponse.json(); loading.remove(); addAssistantMessage(summary.extract || `I found ${match.title}, but there was no short summary available.`, 'assistant', 'Wikipedia'); } catch (error) { loading.remove(); addAssistantMessage('I could not reach a public source right now. Try a CPM question or check your connection and ask again.'); } }
function openAssistant() { $('#assistant-panel').classList.add('is-open'); $('#assistant-panel').removeAttribute('inert'); $('#assistant-input').focus(); }
function closeAssistant() { $('#assistant-panel').classList.remove('is-open'); $('#assistant-panel').setAttribute('inert', ''); $('#assistant-launcher').focus(); }
function updateAccountUI() { $('#account-status').textContent = currentAccount ? `ID ${currentAccount.parkingId}` : 'Guest mode'; $('#account-button').innerHTML = currentAccount ? 'Log out <span>↗</span>' : 'Log in <span>↗</span>'; }
function renderAnalytics() {
  const accountLabel = currentAccount ? `ID ${currentAccount.parkingId}` : 'Sign in to view';
  const personalDriver = currentAccount ? `@${currentAccount.parkingId.toLowerCase()}` : '';
  const personalCars = currentAccount ? cars.filter((car) => car.driver === personalDriver) : [];
  const rankedCars = [...cars].sort((a, b) => b.votes - a.votes);
  const totalVotes = personalCars.reduce((sum, car) => sum + car.votes, 0);
  const bestRank = personalCars.length ? Math.min(...personalCars.map((car) => rankedCars.findIndex((item) => item.id === car.id) + 1)) : 0;
  $('#garage-account').textContent = accountLabel;
  $('#analytics-votes').textContent = currentAccount ? totalVotes : '--';
  $('#analytics-cars').textContent = currentAccount ? personalCars.length : '--';
  $('#analytics-rank').textContent = bestRank ? `#${bestRank}` : '--';
  $('#analytics-rate').textContent = personalCars.length ? (totalVotes / personalCars.length).toFixed(1) : '--';
  $('#garage-login').hidden = Boolean(currentAccount);
  $('#garage-list').innerHTML = !currentAccount ? '<p class="garage-empty">Your personal performance data is private. Sign in to view your cars and analytics.</p>' : personalCars.length ? personalCars.map((car) => { const rank = rankedCars.findIndex((item) => item.id === car.id) + 1; return `<article class="garage-row"><div><strong>${escapeHtml(car.name)}</strong><small>${car.game === 'demo' ? 'CPM Demo' : 'CPM'} · current rank #${rank}</small></div><div class="garage-metric"><b>${car.votes}</b><span>votes</span></div><div class="garage-bar"><span style="width:${Math.min(100, car.votes * 10)}%"></span></div></article>`; }).join('') : '<p class="garage-empty">No cars posted yet. Submit your first build to start tracking its performance.</p>';
}
function openAuth(mode = 'login') { authMode = mode; $('#auth-backdrop').hidden = false; document.querySelectorAll('[data-auth-mode]').forEach((button) => button.classList.toggle('active', button.dataset.authMode === authMode)); document.querySelectorAll('.signup-only').forEach((field) => { field.hidden = authMode !== 'signup'; field.required = authMode === 'signup'; }); $('#auth-title').innerHTML = authMode === 'signup' ? 'CLAIM YOUR<br /><em>DRIVER ID.</em>' : 'ENTER THE<br /><em>DRIVER GRID.</em>'; $('#auth-submit').innerHTML = `${authMode === 'signup' ? 'Create account' : 'Log in'} <span>→</span>`; $('#auth-note').textContent = 'Demo verification checks the ID format in this browser. Production verification must use a server-side CPM account service.'; $('#parking-id').focus(); }
function closeAuth() { $('#auth-backdrop').hidden = true; }
function requireAccount() { if (currentAccount) return true; openAuth(); toast('Log in with your Car Parking ID to continue.'); return false; }
function save() { localStorage.setItem('garageCars', JSON.stringify(cars)); localStorage.setItem('garageVotes', JSON.stringify(voted)); }
function renderCars() {
  const visible = cars.filter((car) => activeFilter === 'all' || car.game === activeFilter);
  $('#car-grid').innerHTML = visible.map((car, index) => `<article class="car-card text-only-card" style="animation-delay:${index * 70}ms"><div class="car-photo"><span class="number">0${index + 1} / 05</span><span class="card-mark">GW</span><button class="vote-button ${voted.includes(car.id) ? 'voted' : ''}" data-vote="${escapeHtml(car.id)}" aria-label="Vote for ${escapeHtml(car.name)}">${voted.includes(car.id) ? '♥' : '♡'}</button></div><div class="car-meta"><strong>${escapeHtml(car.name)}</strong><small>${escapeHtml(car.driver)} · ${car.game === 'demo' ? 'CPM Demo' : 'CPM'}</small><div class="car-votes"><b>${car.votes}</b> votes</div><div class="comment-list">${car.comments.map((comment) => `<p><b>${escapeHtml(comment.author)}</b> ${escapeHtml(comment.text)}</p>`).join('')}</div><form class="comment-form" data-comment-car="${escapeHtml(car.id)}"><input name="comment" maxlength="20" required placeholder="Comment · 20 chars max" aria-label="Comment on ${escapeHtml(car.name)}" /><button type="submit" aria-label="Post comment">→</button></form></div></article>`).join('');
}
function renderLeaderboard() {
  const sorted = [...cars].sort((a, b) => b.votes - a.votes).slice(0, 5);
  $('#leaderboard-list').innerHTML = sorted.map((car, index) => `<div class="leader-row"><span class="pos">0${index + 1}</span><div style="display:flex;align-items:center;gap:12px"><span class="avatar avatar-mark">${String(index + 1).padStart(2, '0')}</span><span class="driver-name">${escapeHtml(car.name)}<small>${escapeHtml(car.driver)}</small></span></div><span class="leader-votes"><b>${car.votes}</b> votes</span></div>`).join('');
  $('#spotlight-stack').innerHTML = sorted.slice(0, 3).map((car, index) => `<div class="spotlight"><span class="spotlight-index">0${index + 1}</span><span><strong>${escapeHtml(car.name)}</strong>${escapeHtml(car.driver)}</span></div>`).join('');
}
function render() { renderCars(); renderLeaderboard(); renderAnalytics(); }
$('#car-grid').addEventListener('click', (event) => { const button = event.target.closest('[data-vote]'); if (!button || !requireAccount()) return; const id = button.dataset.vote; if (voted.includes(id)) { toast('You already voted for this build this week.'); return; } const car = cars.find((item) => item.id === id); car.votes += 1; voted.push(id); save(); render(); toast(`Vote locked for ${car.name}.`); });
$('#car-grid').addEventListener('submit', (event) => { const form = event.target.closest('[data-comment-car]'); if (!form) return; event.preventDefault(); if (!requireAccount()) return; const input = form.elements.comment; const text = input.value.trim().slice(0, 20); if (!text) return; const car = cars.find((item) => item.id === form.dataset.commentCar); if (!car) return; car.comments = Array.isArray(car.comments) ? car.comments : []; car.comments.push({ text, author: `@${currentAccount.parkingId.toLowerCase()}` }); car.comments = car.comments.slice(-20); save(); render(); toast('Comment posted.'); });
document.querySelectorAll('[data-filter]').forEach((button) => button.addEventListener('click', () => { activeFilter = button.dataset.filter; document.querySelectorAll('[data-filter]').forEach((item) => item.classList.toggle('selected', item === button)); renderCars(); }));
document.querySelectorAll('[data-scroll]').forEach((button) => button.addEventListener('click', () => document.querySelector(button.dataset.scroll).scrollIntoView({ behavior: 'smooth' })));
const navLinks = [...document.querySelectorAll('.main-nav a[href^="#"]')];
const navSections = navLinks.map((link) => document.querySelector(link.getAttribute('href'))).filter(Boolean);
const sectionObserver = new IntersectionObserver((entries) => { const visible = entries.filter((entry) => entry.isIntersecting).sort((a, b) => b.intersectionRatio - a.intersectionRatio)[0]; if (!visible) return; navLinks.forEach((link) => { const active = link.getAttribute('href') === `#${visible.target.id}`; link.classList.toggle('active', active); link.toggleAttribute('aria-current', active); }); }, { rootMargin: '-24% 0px -60% 0px', threshold: [0, .25, .5] });
navSections.forEach((section) => sectionObserver.observe(section));
$('#garage-launcher').addEventListener('click', () => { if (!requireAccount()) return; $('#my-garage').scrollIntoView({ behavior: 'smooth' }); });
$('#submit-form').addEventListener('submit', (event) => { event.preventDefault(); if (!requireAccount()) return; const form = new FormData(event.currentTarget); const newCar = cleanCar({ id: `custom-${Date.now()}`, name: form.get('buildName').toString().toUpperCase(), driver: `@${currentAccount.parkingId.toLowerCase()}`, game: form.get('game'), votes: 0 }); cars.unshift(newCar); save(); render(); event.currentTarget.reset(); $('#form-note').textContent = 'Entry added to the top of the grid. Good luck this week.'; toast('Your verified build is live on the grid.'); $('#showcase-grid').scrollIntoView({ behavior: 'smooth' }); });
$('#account-button').addEventListener('click', () => { if (currentAccount) { currentAccount = null; localStorage.removeItem('garageSession'); updateAccountUI(); renderAnalytics(); toast('You are logged out.'); } else openAuth(); });
$('#garage-login').addEventListener('click', openAuth);
$('#advertiser-inquiry-form').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const inquiry = { company: form.get('company').toString().trim(), email: form.get('email').toString().trim(), slot: form.get('slot').toString(), message: form.get('message').toString().trim(), submittedAt: new Date().toISOString() }; const inquiries = Array.isArray(readStorage('advertiserInquiries', [])) ? readStorage('advertiserInquiries', []) : []; inquiries.push(inquiry); localStorage.setItem('advertiserInquiries', JSON.stringify(inquiries)); event.currentTarget.reset(); $('#advertiser-note').textContent = 'Inquiry saved in this browser. A production site should forward this to your sales inbox.'; toast('Your placement inquiry is ready for review.'); });
$('#paypal-payment-form').addEventListener('submit', (event) => { const selection = $('#paypal-slot').value; if (!selection) { event.preventDefault(); toast('Choose an advertising slot before continuing to PayPal.'); return; } const [slot, amount] = selection.split('|'); $('#paypal-item').value = `Garage Weekly - ${slot}`; $('#paypal-amount').value = amount; });
$('#auth-close').addEventListener('click', closeAuth);
$('#auth-backdrop').addEventListener('click', (event) => { if (event.target === event.currentTarget) closeAuth(); });
document.addEventListener('keydown', (event) => { if (event.key !== 'Escape') return; if (!$('#auth-backdrop').hidden) closeAuth(); if ($('#assistant-panel').classList.contains('is-open')) closeAssistant(); });
document.querySelectorAll('[data-auth-mode]').forEach((button) => button.addEventListener('click', () => openAuth(button.dataset.authMode)));
$('#auth-form').addEventListener('submit', (event) => { event.preventDefault(); const form = new FormData(event.currentTarget); const parkingId = form.get('parkingId').toString().trim().toUpperCase(); const passcode = form.get('passcode').toString(); if (!validParkingId(parkingId)) { $('#auth-note').textContent = 'Enter a valid Car Parking ID using 6–24 letters, numbers, or hyphens.'; return; } if (authMode === 'signup') { if (accounts.some((account) => account.parkingId === parkingId)) { $('#auth-note').textContent = 'That Car Parking ID is already registered in this browser.'; return; } accounts.push({ parkingId, passcode, email: form.get('email').toString().trim() }); localStorage.setItem('garageAccounts', JSON.stringify(accounts)); } else if (!accounts.some((account) => account.parkingId === parkingId && account.passcode === passcode)) { $('#auth-note').textContent = 'ID or passcode not recognized. Sign up first on this device.'; return; } currentAccount = { parkingId }; localStorage.setItem('garageSession', JSON.stringify(currentAccount)); updateAccountUI(); renderAnalytics(); closeAuth(); toast(`Verified as ${parkingId}.`); });
$('#assistant-launcher').addEventListener('click', openAssistant);
$('#assistant-close').addEventListener('click', closeAssistant);
$('#assistant-form').addEventListener('submit', (event) => { event.preventDefault(); const input = $('#assistant-input'); const query = input.value.trim(); if (!query) return; addAssistantMessage(query, 'user'); input.value = ''; answerAssistant(query); });
document.querySelectorAll('[data-assistant-prompt]').forEach((button) => button.addEventListener('click', () => { $('#assistant-input').value = button.dataset.assistantPrompt; $('#assistant-form').requestSubmit(); }));
addAssistantMessage('Hi, I am AI Mechanic. Ask me about this community, CPM, or a topic you want to research.');
function updateCountdown() { const now = new Date(); const nextSunday = new Date(now); nextSunday.setDate(now.getDate() + (7 - now.getDay()) % 7); nextSunday.setHours(23, 59, 59, 0); if (nextSunday <= now) nextSunday.setDate(nextSunday.getDate() + 7); let seconds = Math.max(0, Math.floor((nextSunday - now) / 1000)); const days = Math.floor(seconds / 86400); seconds %= 86400; const hours = Math.floor(seconds / 3600); seconds %= 3600; const minutes = Math.floor(seconds / 60); seconds %= 60; $('#days').textContent = String(days).padStart(2, '0'); $('#hours').textContent = String(hours).padStart(2, '0'); $('#minutes').textContent = String(minutes).padStart(2, '0'); $('#seconds').textContent = String(seconds).padStart(2, '0'); }
updateAccountUI(); render(); updateCountdown(); setInterval(updateCountdown, 1000);
